version: 2
updates:
  # Rust dependencies
  - package-ecosystem: "cargo"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:00"
    assignees:
      - "chrischtel" 
    labels:
      - "dependencies"
      - "rust"
    commit-message:
      prefix: "deps"
      include: "scope"

  # Frontend Rust dependencies
  - package-ecosystem: "cargo" 
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:30"
    assignees:
      - "chrischtel"
    labels:
      - "dependencies"
      - "component: frontend"
    commit-message:
      prefix: "deps(frontend)"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "04:00"
    assignees:
      - "chrischtel"
    labels:
      - "dependencies"
      - "type: ci"
    commit-message:
      prefix: "ci"
